apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment2
  namespace: volume2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app2
  template:
    metadata:
      labels:
        app: multi-container-app2
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "$(date) - Hello_from_Busybox!" >> /busy_dir/data.log; sleep 5; done']
        volumeMounts:
        - name: my-vol-pvc
          mountPath: "/busy_dir"

      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /multitool_dir/data.log']
        volumeMounts:
        - name: my-vol-pvc
          mountPath: "/multitool_dir"
      volumes:
      - name: my-vol-pvc
        persistentVolumeClaim:
          claimName: pvc-vol